name: Count Insertions Per Commit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  count-insertions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Collaborator Commits - lind-exe
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/lind-exe/Statify/commits?author=lind-exe" > lind-exe_commits.json

      - name: Get Collaborator Commits - dantrew
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/lind-exe/Statify/commits?author=dantrew" > dantrew_commits.json

      - name: Count Insertions - lind-exe
        run: |
          total_insertions_lind_exe=0
          if [ -f lind-exe_commits.json ]; then
            for sha in $(jq -r '.[].sha' lind-exe_commits.json); do
              insertions=$(git diff --shortstat $sha^ $sha | grep 'insertion' | awk '{print $1}')
              total_insertions_lind_exe=$((total_insertions_lind_exe + insertions))
            done
          fi
          echo "::set-output name=total_insertions_lind_exe::$total_insertions_lind_exe"

      - name: Count Insertions - dantrew
        run: |
          total_insertions_dantrew=0
          if [ -f dantrew_commits.json ]; then
            for sha in $(jq -r '.[].sha' dantrew_commits.json); do
              insertions=$(git diff --shortstat $sha^ $sha | grep 'insertion' | awk '{print $1}')
              total_insertions_dantrew=$((total_insertions_dantrew + insertions))
            done
          fi
          echo "::set-output name=total_insertions_dantrew::$total_insertions_dantrew"

      - name: Display Insertions Count
        run: |
          echo "Total insertions made by lind-exe: ${{ steps.count-insertions.outputs.total_insertions_lind_exe }}"
          echo "Total insertions made by dantrew: ${{ steps.count-insertions.outputs.total_insertions_dantrew }}"
