name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Install Coverlet Global Tool
        run: dotnet tool install --global coverlet.console

      - name: Run Tests with Coverlet
        run: dotnet test --collect:"XPlat Code Coverage" --settings $(Build.SourcesDirectory)\coverlet.runsettings

      - name: Generate Cobertura Report with ReportGenerator
        run: ReportGenerator -reports:$(Build.SourcesDirectory)/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:Cobertura

      - name: Run SonarScanner
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"my-project" /o:"lind-exe" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.coverageReportPaths="coveragereport/Cobertura.xml"
          dotnet build
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"


